export const AGREGAR_FISCALIA = "AGREGAR_FISCALIA";
export const AGREGAR_FISCALIA_EXITO = "AGREGAR_FISCALIA_EXITO";
export const AGREGAR_FISCALIA_ERROR = "AGREGAR_FISCALIA_ERROR";

export const COMENZAR_DESCARGA_FISCALIAS = "COMENZAR_DESCARGA_FISCALIAS";
export const DESCARGA_FISCALIAS_EXITO = "DESCARGA_FISCALIAS_EXITO";
export const COMENZAR_DESCARGA_FISCALIAS_ERROR =
  "COMENZAR_DESCARGA_FISCALIAS_ERROR";

export const OBTENER_FISCALIA_ELIMINAR = "OBTENER_FISCALIA_ELIMINAR";
export const FISCALIA_ELIMINADO_EXITO = "FISCALIA_ELIMINADO_EXITO";
export const FISCALIA_ELIMINADO_ERROR = "FISCALIA_ELIMINADO_ERROR";

export const OBTENER_FISCALIA_EDITAR = "OBTENER_FISCALIA_EDITAR";
export const COMENZAR_EDICION_FISCALIA = "COMENZAR_EDICION_FISCALIA";
export const FISCALIA_EDITADO_EXITO = "FISCALIA_EDITADO_EXITO";
export const FISCALIA_EDITADO_ERROR = "FISCALIA_EDITADO_ERROR";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

//Deptos
export const COMENZAR_DESCARGA_DEPARTAMENTOS =  "COMENZAR_DESCARGA_DEPARTAMENTOS";
export const DESCARGA_DEPARTAMENTOS_EXITO = "DESCARGA_DEPARTAMENTOS_EXITO";
export const COMENZAR_DESCARGA_DEPARTAMENTOS_ERROR =  "COMENZAR_DESCARGA_DEPARTAMENTOS_ERROR";

//mpio
export const COMENZAR_DESCARGA_MPIO       =  "COMENZAR_DESCARGA_MPIO";
export const DESCARGA_MPIO_EXITO          =        "DESCARGA_MPIO_EXITO";
export const COMENZAR_DESCARGA_MPIO_ERROR =  "COMENZAR_DESCARGA_MPIO_ERROR";


//tipos
export const COMENZAR_DESCARGA_TIPO       =  "COMENZAR_DESCARGA_TIPO";
export const DESCARGA_TIPO_EXITO          =        "DESCARGA_TIPO_EXITO";
export const COMENZAR_DESCARGA_TIPO_ERROR =  "COMENZAR_DESCARGA_TIPO_ERROR";
